### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by cyrilschreiber3** [cyrilschreiber3/nixconfig#1]
Things left to do before daily driving:
- [x] Pass DE to Cinnamom
- [ ] Configure Discord + BetterDiscord
- [x] Setup full pass through windows VM
- [x] Configure Obsidian
- [x] Install laptop-specific hardware tweaks
- [x] Fix screen through docking station
- [x] Stop spotify from sending notifications for each song
- [ ] Fix screen colors
- [x] automate screen configuration detection
- [x] Fix icon transparent in start menu
- [x] Add Diodon clipboard manager
- [ ] Binary cache + local nixpkgs cache
- [x] Use overlays for stable packages and my packages
- [x] Fix desktop audio loopback
- [ ] Use nix run command for initial install script
